---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    waitTime: "{1,number,integer}"
  labels:
    run: {0}
  name: {0}
spec:
  containers:
  - command:
    - sleep
    - "{1,number,integer}"
    image: busybox
    name: sleeper
  dnsPolicy: ClusterFirst
  restartPolicy: Always
